runner.dialect = Scala213Source3
version = 3.11.0
maxColumn = 130
continuationIndent.defnSite = 2
rewrite.rules = [RedundantBraces, RedundantParens, SortImports]
rewrite.redundantBraces.parensForOneLineApply = false
rewrite.redundantBraces.generalExpressions = false
docstrings.blankFirstLine = yes
docstrings.style = SpaceAsterisk
docstrings.wrap = no

fileOverride {
  "glob:**/*.sbt" {
    align.preset = most
  }
}
