addSbtPlugin("org.scoverage"    % "sbt-scoverage"   % "2.4.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"    % "2.5.6")
addSbtPlugin("org.wartremover"  % "sbt-wartremover" % "3.5.6")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"     % "0.6.3")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"  % "1.11.2")
addSbtPlugin("com.typesafe"     % "sbt-mima-plugin" % "1.1.5")
addSbtPlugin("com.github.sbt"  %% "sbt-sbom"        % "0.5.0")
