name: Layers Build

on: [ push, pull_request ]

jobs:
  scala:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
          cache: sbt

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Run QA
        run: |
          mkdir ${{ github.workspace }}/target
          sbt qa

      - name: Push Coverage Result
        uses: codecov/codecov-action@v4
        with:
          flags: scala
          token: ${{ secrets.CODECOV_TOKEN }}
